export enum PaymentMode {
  ONLINE_PAYMENT = "ONLINE_PAYMENT",
  ONSITE_PAYMENT = "ONSITE_PAYMENT",
}

export enum PaymentMethod {
  MULTICAIXA_EXPRESS = "MULTICAIXA_EXPRESS",
  REFERENCE = "REFERENCE",
  ONSITE_CARD = "ONSITE_CARD",
}
