export enum VerificationType {
    WITHDRAWAL = "WITHDRAWAL",
    CHANGE_PASSWORD = "CHANGE_PASSWORD",
    RESET_PASSWORD = "RESET_PASSWORD",
    CHANGE_BANK = "CHANGE_BANK",
    LOGIN = "LOGIN",
    DELETE_ACCOUNT = "DELETE_ACCOUNT",
    DISABLE_SECURE = "DISABLE_SECURE",
}